[project]
name = "comp-uid"
version = "0.1.0"
description = "A simple python script to retrieve and compare linux users and their uid's"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
